// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWpRFOLYkFuvKqWC_YaA0DBJETROo_j3k',
    appId: '1:561772756040:web:4f36f722df77b10f41ec7d',
    messagingSenderId: '561772756040',
    projectId: 'mombien',
    authDomain: 'mombien.firebaseapp.com',
    databaseURL: 'https://mombien-default-rtdb.firebaseio.com',
    storageBucket: 'mombien.appspot.com',
    measurementId: 'G-XEEBC5VEXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFJ-NEIWUsH0Dw6o4X-MU7USffkEfQS2g',
    appId: '1:561772756040:android:736d1ba29091a7f041ec7d',
    messagingSenderId: '561772756040',
    projectId: 'mombien',
    databaseURL: 'https://mombien-default-rtdb.firebaseio.com',
    storageBucket: 'mombien.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-_Zj2dAgs8GAEUbjZb10aSEvHXVfLdH8',
    appId: '1:561772756040:ios:4de3db76a230234f41ec7d',
    messagingSenderId: '561772756040',
    projectId: 'mombien',
    databaseURL: 'https://mombien-default-rtdb.firebaseio.com',
    storageBucket: 'mombien.appspot.com',
    androidClientId:
        '561772756040-ind1719i4omcvb2efs1h2erl8h7dss1k.apps.googleusercontent.com',
    iosClientId:
        '561772756040-1sln6mudspha5pcap5gldjunqp1goe1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mombienTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-_Zj2dAgs8GAEUbjZb10aSEvHXVfLdH8',
    appId: '1:561772756040:ios:4de3db76a230234f41ec7d',
    messagingSenderId: '561772756040',
    projectId: 'mombien',
    databaseURL: 'https://mombien-default-rtdb.firebaseio.com',
    storageBucket: 'mombien.appspot.com',
    androidClientId:
        '561772756040-ind1719i4omcvb2efs1h2erl8h7dss1k.apps.googleusercontent.com',
    iosClientId:
        '561772756040-1sln6mudspha5pcap5gldjunqp1goe1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.mombienTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWpRFOLYkFuvKqWC_YaA0DBJETROo_j3k',
    appId: '1:561772756040:web:2429fd9e8c7d909f41ec7d',
    messagingSenderId: '561772756040',
    projectId: 'mombien',
    authDomain: 'mombien.firebaseapp.com',
    databaseURL: 'https://mombien-default-rtdb.firebaseio.com',
    storageBucket: 'mombien.appspot.com',
    measurementId: 'G-8YZ2Q9SLQT',
  );
}
